# URL corrigida para o Host de Banco de Dados do Supabase
# O Host correto é db.wjjcznjpcnvqnhfwbbyk.supabase.co
flyway.url=jdbc:postgresql://db.wjjcznjpcnvqnhfwbbyk.supabase.co:6543/postgres?sslmode=require&prepareThreshold=0

# USUÁRIO: No Supabase, para conexões JDBC/Postgres, use sempre 'postgres'
# O código 'sb_publishable...' é uma chave de API e NÃO funciona aqui.
flyway.user=postgres

# SENHA: A senha do banco de dados que você definiu na criação do projeto
flyway.password=Projetowanderson2020

flyway.schemas=public

# CAMINHO: Removida a barra final para evitar erros de leitura no Flyway
flyway.locations=filesystem:./database/migrate/app_auth

flyway.connectRetries=10

# Mantém a conexão limpa para evitar erros de Pooler
flyway.jdbcProperties.cleanup_connection=true