# URL de conexão (Substitua [YOUR-PASSWORD] pela sua senha real)
flyway.url=jdbc:postgresql://db.skfkpylshcgtpjxgkska.supabase.co:5432/postgres

# O SEGREDO: O usuário deve seguir o padrão 'postgres.ID_DO_PROJETO' 
# ou apenas 'postgres' se a senha estiver correta, mas o host do Supabase 
# exige o ID do projeto para roteamento.
flyway.user=postgres.skfkpylshcgtpjxgkska
flyway.password=Projetowanderson

# Locais das migrações
flyway.locations=filesystem:./database/migrate/crm_whatsapp